font:
   normal:
      family:              monospace
   size:                   10

cursor:
   style:                  Beam

url:
   program:                xdg-open
colors:
   primary: 
      background:          '0x000000'
      foreground:          '0xffffff'
   selection:
      text:                '0xffffff'
      background:          '0x404040'
   normal:
      black:               '0x000000'
      red:                 '0xff0000'
      green:               '0x00ff00'
      yellow:              '0xffff00'
      blue:                '0x0077ff'
      magenta:             '0xff00ff'
      cyan:                '0x00ddff'
      white:               '0xffffff'
   bright:
      black:               '0x000000'
      red:                 '0xff0000'
      green:               '0x00ff00'
      yellow:              '0xffff00'
      blue:                '0x0077ff'
      magenta:             '0xff00ff'
      cyan:                '0x00ddff'
      white:               '0xffffff'
   
background_opacity:        0.7
