
"--------------Basic Settings--------------

"set runtime so packages work
runtime! archlinux.vim
"fast scroll yeet
set ttyfast
"sexy ass statusbar
set laststatus=1
set showmode
set showcmd
"turn off modelines
set modelines=0

"--------------Programming Stuff--------------
"syntax
filetype off
syntax on                
filetype plugin indent on
set matchpairs+=<:>
"spaces > tabs
set tabstop=3 shiftwidth=2 expandtab
retab
"line numbers
set number
set numberwidth=3

