#! /bin/sh
for x in $(bspc query -M);
do bspc monitor $x -d 1 2 3;
done
#gaps and borders
bspc config border_width          1
bspc config window_gap            10
#tiling bullshit
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
#general config
bspc config focus_follows_pointer true
bspc config focused_border_color '#161616'
#window rules
#bspc rule -a rofi focus=on
#bspc rule -a rofi layer=above
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating
bspc rule -a plasmashell state=floating manage=off layer=normal
bspc rule -a Plasma state=floating manage=off layer=normal
autostart & 
